In [2]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

# For this assignment you need to complete 8 of the following exercises against this data.

## Note: You must select at least two methods from each chapter to perform on one of the datasets. You are welcome to do more methods and you do not have to use the same dataset for all 8 methods.

In [3]:
#Decided to use So Much Candy. Opening xlsx file from website
url = 'https://www.scq.ubc.ca/wp-content/uploads/2017/10/candyhierarchy2017.xlsx'
df = pd.read_excel(url, header=0)
df #I show 2460 rows and 120 columns

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

## Chapter 7

In [4]:
#Filter out missing data
#This will show me how many null values are in each column
for c in df.columns:
    miss = df[c].isnull().sum()
    if miss>0:
        print("{} has {} missing value(s)".format(c,miss))
    else:
        print("{} has no missing values".format(c))

Internal ID has no missing values
Q1: GOING OUT? has 110 missing value(s)
Q2: GENDER has 41 missing value(s)
Q3: AGE has 84 missing value(s)
Q4: COUNTRY has 64 missing value(s)
Q5: STATE, PROVINCE, COUNTY, ETC has 100 missing value(s)
Q6 | 100 Grand Bar has 747 missing value(s)
Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes) has 734 missing value(s)
Q6 | Any full-sized candy bar has 672 missing value(s)
Q6 | Black Jacks has 958 missing value(s)
Q6 | Bonkers (the candy) has 992 missing value(s)
Q6 | Bonkers (the board game) has 1006 missing value(s)
Q6 | Bottle Caps has 765 missing value(s)
Q6 | Box'o'Raisins has 688 missing value(s)
Q6 | Broken glow stick has 706 missing value(s)
Q6 | Butterfinger has 682 missing value(s)
Q6 | Cadbury Creme Eggs has 683 missing value(s)
Q6 | Candy Corn has 678 missing value(s)
Q6 | Candy that is clearly just the stuff given out for free at restaurants has 691 missing value(s)
Q6 | Caramellos has 752 missing value(s)
Q6 | Cash, or other forms of legal tender has 680 missing value(s)
Q6 | Chardonnay has 743 missing value(s)
Q6 | Chick-o-Sticks (we don’t know what that is) has 946 missing value(s)
Q6 | Chiclets has 711 missing value(s)
Q6 | Coffee Crisp has 853 missing value(s)
Q6 | Creepy Religious comics/Chick Tracts has 704 missing value(s)
Q6 | Dental paraphenalia has 692 missing value(s)
Q6 | Dots has 729 missing value(s)
Q6 | Dove Bars has 702 missing value(s)
Q6 | Fuzzy Peaches has 823 missing value(s)
Q6 | Generic Brand Acetaminophen has 731 missing value(s)
Q6 | Glow sticks has 697 missing value(s)
Q6 | Goo Goo Clusters has 879 missing value(s)
Q6 | Good N' Plenty has 734 missing value(s)
Q6 | Gum from baseball cards has 716 missing value(s)
Q6 | Gummy Bears straight up has 697 missing value(s)
Q6 | Hard Candy has 695 missing value(s)
Q6 | Healthy Fruit has 694 missing value(s)
Q6 | Heath Bar has 712 missing value(s)
Q6 | Hershey's Dark Chocolate has 673 missing value(s)
Q6 | Hershey’s Milk Chocolate has 672 missing value(s)
Q6 | Hershey's Kisses has 678 missing value(s)
Q6 | Hugs (actual physical hugs) has 713 missing value(s)
Q6 | Jolly Rancher (bad flavor) has 694 missing value(s)
Q6 | Jolly Ranchers (good flavor) has 695 missing value(s)
Q6 | JoyJoy (Mit Iodine!) has 1026 missing value(s)
Q6 | Junior Mints has 698 missing value(s)
Q6 | Senior Mints has 942 missing value(s)
Q6 | Kale smoothie has 744 missing value(s)
Q6 | Kinder Happy Hippo has 945 missing value(s)
Q6 | Kit Kat has 674 missing value(s)
Q6 | LaffyTaffy has 736 missing value(s)
Q6 | LemonHeads has 730 missing value(s)
Q6 | Licorice (not black) has 686 missing value(s)
Q6 | Licorice (yes black) has 685 missing value(s)
Q6 | Lindt Truffle has 718 missing value(s)
Q6 | Lollipops has 691 missing value(s)
Q6 | Mars has 725 missing value(s)
Q6 | Maynards has 1024 missing value(s)
Q6 | Mike and Ike has 729 missing value(s)
Q6 | Milk Duds has 693 missing value(s)
Q6 | Milky Way has 688 missing value(s)
Q6 | Regular M&Ms has 675 missing value(s)
Q6 | Peanut M&M’s has 671 missing value(s)
Q6 | Blue M&M's has 727 missing value(s)
Q6 | Red M&M's has 729 missing value(s)
Q6 | Green Party M&M's has 764 missing value(s)
Q6 | Independent M&M's has 813 missing value(s)
Q6 | Abstained from M&M'ing. has 942 missing value(s)
Q6 | Minibags of chips has 724 missing value(s)
Q6 | Mint Kisses has 776 missing value(s)
Q6 | Mint Juleps has 811 missing value(s)
Q6 | Mr. Goodbar has 740 missing value(s)
Q6 | Necco Wafers has 744 missing value(s)
Q6 | Nerds has 723 missing value(s)
Q6 | Nestle Crunch has 698 missing value(s)
Q6 | Now'n'Laters has 817 missing value(s)
Q6 | Peeps has 710 missing value(s)
Q6 | Pencils has 709 missing value(s)
Q6 | Pixy Stix has 722 missing value(s)
Q6 | Real Housewives of Orange County Season 9 Blue-Ray has 753 missing value(s)
Q6 | Reese’s Peanut Butter Cups has 679 missing value(s)
Q6 | Reese's Pieces has 691 missing value(s)
Q6 | Reggie Jackson Bar has 1014 missing value(s)
Q6 | Rolos has 714 missing value(s)
Q6 | Sandwich-sized bags filled with BooBerry Crunch has 776 missing value(s)
Q6 | Skittles has 706 missing value(s)
Q6 | Smarties (American) has 725 missing value(s)
Q6 | Smarties (Commonwealth) has 901 missing value(s)
Q6 | Snickers has 690 missing value(s)
Q6 | Sourpatch Kids (i.e. abominations of nature) has 738 missing value(s)
Q6 | Spotted Dick has 882 missing value(s)
Q6 | Starburst has 693 missing value(s)
Q6 | Sweet Tarts has 708 missing value(s)
Q6 | Swedish Fish has 715 missing value(s)
Q6 | Sweetums (a friend to diabetes) has 1002 missing value(s)
Q6 | Take 5 has 917 missing value(s)
Q6 | Tic Tacs has 714 missing value(s)
Q6 | Those odd marshmallow circus peanut things has 736 missing value(s)
Q6 | Three Musketeers has 708 missing value(s)
Q6 | Tolberone something or other has 706 missing value(s)
Q6 | Trail Mix has 708 missing value(s)
Q6 | Twix has 690 missing value(s)
Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein has 792 missing value(s)
Q6 | Vicodin has 789 missing value(s)
Q6 | Whatchamacallit Bars has 823 missing value(s)
Q6 | White Bread has 757 missing value(s)
Q6 | Whole Wheat anything has 747 missing value(s)
Q6 | York Peppermint Patties has 705 missing value(s)
Q7: JOY OTHER has 1549 missing value(s)
Q8: DESPAIR OTHER has 1743 missing value(s)
Q9: OTHER COMMENTS has 2074 missing value(s)
Q10: DRESS has 744 missing value(s)
Unnamed: 113 has 2451 missing value(s)
Q11: DAY has 725 missing value(s)
Q12: MEDIA [Daily Dish] has 2375 missing value(s)
Q12: MEDIA [Science] has 1098 missing value(s)
Q12: MEDIA [ESPN] has 2361 missing value(s)
Q12: MEDIA [Yahoo] has 2393 missing value(s)
Click Coordinates (x, y) has 855 missing value(s)

In [5]:
#To remove them I'm using dropna but specifying a threshold. Using a higher number because some of the columns barely have any data
df_drop = df.dropna(thresh=100)
df_drop #Now I have 1537 rows and 120 columns. When I tried just dropna without specifying a threshold it went to no data. I'm assuming at this point every row has some piece of missing data which is why I moved to this method.

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(55, 5)"
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(76, 24)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2453,90313974,No,Female,40,canada,bc,MEH,DESPAIR,JOY,DESPAIR,...,Maltesers,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(68, 29)"
2454,90314022,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(68, 39)"
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [6]:
#Drop duplicates
#Since many of the other columns are likely to have duplicate values I only want to drop any duplicate Internal ID as that is the primary key for this data
df_candy = df_drop.drop_duplicates(['Internal ID'])
df_candy #Had no duplicates among Internal ID

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(55, 5)"
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(76, 24)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2453,90313974,No,Female,40,canada,bc,MEH,DESPAIR,JOY,DESPAIR,...,Maltesers,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(68, 29)"
2454,90314022,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(68, 39)"
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

## Chapter 8

In [7]:
#First I'm going to split the original dataframe into two separate subsets so I can practice putting them back together again
df_male = df_candy[df_candy["Q2: GENDER"].isin(["Male"])] #Created a subset of only male responses
df_female = df_candy[df_candy["Q2: GENDER"].isin(["Female"])] #Created a subset of only female responses
df_female.head() #Just taking a peek to make sure it worked as expected

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
9,90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(70, 28)"
14,90272868,No,Female,37,Canada,Ontario,MEH,JOY,JOY,MEH,...,Coupons,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 25)"
23,90272891,No,Female,49,United States,RI,JOY,MEH,JOY,DESPAIR,...,NaN,Suggest all households adopt my tradition of c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,90272904,No,Female,33,Usa,Michigan,JOY,MEH,JOY,DESPAIR,...,"Stigmata, minimum wage jobs",The structural inequalities inherent in candy ...,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
41,90272924,No,Female,48,United staes,Minnesota,JOY,DESPAIR,MEH,DESPAIR,...,Trump,NaN,White and gold,NaN,Friday,1.0,NaN,NaN,NaN,"(16, 32)"

In [8]:
#Now to merge these I'm going to a many-to-one join using gender
df_combo = df_female.combine_first(df_male)
df_combo
#Struggled with this one at first. Tried using merge, but ended up with 239 columns and no rows. Looked further into the chapter and saw data that has overlap use combine_first pg 245

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
1,90272821.0,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
3,90272840.0,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841.0,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
7,90272854.0,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(55, 5)"
8,90272858.0,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(76, 24)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2453,90313974.0,No,Female,40,canada,bc,MEH,DESPAIR,JOY,DESPAIR,...,Maltesers,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(68, 29)"
2454,90314022.0,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(68, 39)"
2455,90314359.0,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2457,90314634.0,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2459,90314802.0,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [9]:
#Reshaping the data using hierarchical indexing pg 247
result = df_combo.stack()
result #Now data is rotated

1     Internal ID                                                       9.02728e+07
      Q1: GOING OUT?                                                             No
      Q2: GENDER                                                               Male
      Q3: AGE                                                                    44
      Q4: COUNTRY                                                              USA
                                                        ...
2459  Q9: OTHER COMMENTS          You hit all my chocolate highlights, and broug...
      Q10: DRESS                                                     White and gold
      Q11: DAY                                                               Sunday
      Q12: MEDIA [Daily Dish]                                                     1
      Click Coordinates (x, y)                                             (19, 26)
Length: 164018, dtype: object

In [10]:
#Reshaping using unstack
reshaped = result.unstack()
reshaped #Data is pivoted back although not sure why Internal ID is showing like it is now

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
1,9.02728e+07,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1,NaN,NaN,"(84, 25)"
3,9.02728e+07,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1,NaN,NaN,"(75, 23)"
4,9.02728e+07,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1,NaN,NaN,"(70, 10)"
7,9.02729e+07,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,NaN,1,NaN,NaN,"(55, 5)"
8,9.02729e+07,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1,NaN,NaN,"(76, 24)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2453,9.0314e+07,No,Female,40,canada,bc,MEH,DESPAIR,JOY,DESPAIR,...,Maltesers,NaN,White and gold,NaN,Sunday,NaN,1,NaN,NaN,"(68, 29)"
2454,9.0314e+07,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1,NaN,NaN,"(68, 39)"
2455,9.03144e+07,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2457,9.03146e+07,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1,NaN,NaN,"(67, 35)"
2459,9.03148e+07,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1,NaN,NaN,NaN,"(19, 26)"

## Chapter 10

In [11]:
#Going to change datasets for the remainder of the exercises
df_boing = pd.read_excel('BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx')
df_boing.head()

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN

In [12]:
#Going to re-name some of the columns to make the rest of the work easier
df_boing.rename(columns={'Are you going actually going trick or treating yourself?':'Going',
                     'Your gender:':'Gender',
                      'Which country do you live in?':'Country'},
                     inplace=True)
print(df_boing.columns)

Index(['Timestamp', 'Going', 'Gender', 'How old are you?', 'Country',
       'Which state, province, county do you live in?', ' [100 Grand Bar]',
       ' [Anonymous brown globs that come in black and orange wrappers]',
       ' [Any full-sized candy bar]', ' [Black Jacks]',
       ...
       'Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling]',
       'Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Bieber]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]',
       'Which day do you prefer, Friday or Sunday?',
       'Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?',
       'When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).',
       ' [York Peppermint Patties] Ignore'],
      dtype='object', length=123)

In [13]:
#10.3 split-apply-combine
def going(df_boing, n=5, column='Going'):
    return df_boing.sort_values(by=column)[-n:]

going(df_boing, n=20)
#used pg 308 split on whether going trick or treat. I assume I did what I wanted as all I see is yes in the top with the index out of order

,Timestamp,Going,Gender,How old are you?,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
194,2016-10-24 07:26:06.192,Yes,Male,45,United States,Texas,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,I own an Apple corer/slicer,Science: Latest News and Headlines,NaN
1043,2016-10-27 09:24:20.705,Yes,Female,40,usa,WA,MEH,DESPAIR,JOY,MEH,...,2,1,1,3 or higher,1,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
188,2016-10-24 07:22:19.381,Yes,Male,43,Units States,Arizona,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,2,Friday,East to West,Science: Latest News and Headlines,NaN
183,2016-10-24 07:18:33.371,Yes,Male,53,usa,"Texas, Fort Bend",MEH,DESPAIR,MEH,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,YAHOO! Finance.,NaN
1054,2016-10-27 09:47:32.800,Yes,Male,45,Usa,Ca,JOY,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,2,2,Sunday,South to North,Science: Latest News and Headlines,NaN
461,2016-10-24 11:14:31.569,Yes,Male,50,usa,california,JOY,DESPAIR,MEH,NaN,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1056,2016-10-27 09:51:42.462,Yes,Male,35,united states,OR,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1057,2016-10-27 09:51:48.159,Yes,Other,67,China,NaN,DESPAIR,JOY,JOY,MEH,...,2,3 or higher,3 or higher,3 or higher,2,2,Friday,Applesauce,Daily Dish,NaN
180,2016-10-24 07:13:54.510,Yes,Female,13,America,Alabama,MEH,MEH,JOY,MEH,...,3 or higher,1,3 or higher,3 or higher,1,1,Friday,East to West,Daily Dish,NaN
179,2016-10-24 07:12:15.332,Yes,Male,18,US,NaN,MEH,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,East to West,Science: Latest News and Headlines,NaN
1064,2016-10-27 10:24:22.863,Yes,Male,47,usa,fl,NaN,NaN,NaN,NaN,...,1,1,1,1,1,1,Friday,With a knife,Science: Latest News and Headlines,NaN
470,2016-10-24 11:21:17.737,Yes,Male,46,The Yoo Ess of Aaayyyyyy,"Lozangeleeezz, CA",JOY,JOY,JOY,DESPAIR,...,3 or higher,2,2,3 or higher,1,3 or higher,Friday,"Honestly, west to east, initially, then back a...",Science: Latest News and Headlines,NaN
1075,2016-10-27 10:50:07.673,Yes,Male,33,USA,CA,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,1,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
165,2016-10-24 07:03:02.392,Yes,Male,48,USA,Georgia,JOY,DESPAIR,JOY,NaN,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
164,2016-10-24 07:02:46.526,Yes,Male,42,United States,Texas,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
163,2016-10-24 07:02:40.720,Yes,Male,40,USA,Missouri,JOY,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
734,2016-10-24 19:57:33.150,Yes,Male,36,USA,Maryland,MEH,DESPAIR,JOY,MEH,...,2,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,typewriter-style,Science: Latest News and Headlines,NaN
1082,2016-10-27 11:01:43.616,Yes,Female,50,USA,WA,JOY,DESPAIR,DESPAIR,DESPAIR,...,3 or higher,2,3 or higher,3 or higher,2,3 or higher,Sunday,civilly sliced,Science: Latest News and Headlines,NaN
159,2016-10-24 06:57:31.650,Yes,Female,38,USA,MA,JOY,DESPAIR,JOY,MEH,...,2,2,1,3 or higher,3 or higher,"Actually, that's me.",Friday,East to West,Science: Latest News and Headlines,NaN
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

In [14]:
#Perform crosstab using going and gender found on pg 322
pd.crosstab(df_boing.Going, df_boing.Gender, margins=True)

Gender  Female  I'd rather not say  Male  Other   All
Going
No         365                  25   707     16  1113
Yes         45                   3    88      1   137
All        410                  28   795     17  1250

## Chapter 11

In [15]:
#Want to look at dataframe using a specific date range
start_date = '2016-10-24'
end_date = '2016-10-27'
range = (df_boing['Timestamp'] > start_date) & (df_boing['Timestamp'] <= end_date)
df_range = df_boing.loc[range]
df_range
#Only showing data within the date range I had called out. Also now have 966 rows which is less than when I had full data

,Timestamp,Going,Gender,How old are you?,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
961,2016-10-26 18:49:48.549,No,Female,Never ask a woman that question.,USA,Maryland,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN
962,2016-10-26 18:56:06.282,Yes,Male,Not as old as you...,Sub-Canadian North America... 'Merica,"P€##$¥|>@#,@",MEH,DESPAIR,JOY,NaN,...,3 or higher,3 or higher,3 or higher,3 or higher,1,"Actually, that's me.",Friday,South to North,Science: Latest News and Headlines,NaN
963,2016-10-26 18:56:41.117,No,Female,33,United States,New York,MEH,JOY,JOY,NaN,...,2,2,2,2,2,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
964,2016-10-26 21:03:17.790,No,Male,38,United States of America,Virginia,JOY,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
965,2016-10-26 22:11:26.488,No,Other,42,Australia,NaN,MEH,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,NaN,Science: Latest News and Headlines,NaN

In [27]:
#Convert timestamps to period and back
pd.to_datetime(df_boing['Timestamp'], format='%d/%b/%Y:%H:%M:%S')
df_boing['Period'] = pd.DatetimeIndex(df_boing['Timestamp']).to_period('M')
df_boing['Time'] = pd.to_datetime(df_boing['Timestamp'], format='%H:%M').dt.time
df_boing['Time'].iloc[0]
df_boing['ConvertedTime'] = df_boing['Timestamp'].dt.tz_localize('GMT').dt.tz_convert('America/New_York')
df_boing

,Timestamp,Going,Gender,How old are you?,Country,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore,Period,Time,ConvertedTime
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN,2016-10,05:09:23.033000,2016-10-24 01:09:23.033000-04:00
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10,05:09:54.798000,2016-10-24 01:09:54.798000-04:00
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10,05:13:06.734000,2016-10-24 01:13:06.734000-04:00
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN,2016-10,05:14:17.192000,2016-10-24 01:14:17.192000-04:00
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN,2016-10,05:14:24.625000,2016-10-24 01:14:24.625000-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10,16:53:52.516000,2016-10-29 12:53:52.516000-04:00
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN,2016-10,06:53:54.735000,2016-10-30 02:53:54.735000-04:00
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN,2016-10,11:06:10.827000,2016-10-30 07:06:10.827000-04:00
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10,16:07:26.539000,2016-10-30 12:07:26.539000-04:00
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN,2016-10,17:06:45.660000,2016-10-30 13:06:45.660000-04:00